version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: task-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shourov123
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: task-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: development          # ← জোর করে development সেট করা হলো
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app                      # development এর জন্য (optional)

volumes:
  postgres_data: